spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  level:
    com.example: debug
  pattern:
    dateformat: HH:mm:ss

